# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-27 06:55
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django_pgjson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0054_auto_20160928_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttemplate',
            name='epic_custom_attributes',
            field=django_pgjson.fields.JsonField(blank=True, null=True, verbose_name='epic custom attributes'),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='is_looking_for_people',
            field=models.BooleanField(default=False, verbose_name='is looking for people'),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='issue_custom_attributes',
            field=django_pgjson.fields.JsonField(blank=True, null=True, verbose_name='issue custom attributes'),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='looking_for_people_note',
            field=models.TextField(blank=True, default='', verbose_name='loking for people note'),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=[], null=True, size=None, verbose_name='tags'),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='tags_colors',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=2), blank=True, default=[], null=True, size=None, verbose_name='tags colors'),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='task_custom_attributes',
            field=django_pgjson.fields.JsonField(blank=True, null=True, verbose_name='task custom attributes'),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='us_custom_attributes',
            field=django_pgjson.fields.JsonField(blank=True, null=True, verbose_name='us custom attributes'),
        ),
    ]
